version: '3'
services:
  dev-container:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "5005:5005"
      - "4200:4200"
    volumes:
      - ..:/workspaces
    command: sleep infinity


